### ISSUE TITLE
Мне непонятно, в каком случае здесь можно схватить ошибку?

### ISSUE THREAD

**Issue by denis-trofimov** [imzaur/web_project#2]
https://github.com/imzaur/web_project/blob/39433288057e381efc54ab918719f7f7a67839c9/parsing.py#L37-L41

**Comment by imzaur** [comment]
Когда много страниц тем не менее он ее ловит

**Comment by imzaur** [comment]
Причем возвращает все нужные значения, но ловит ошибку в конце.
